#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef SCALECLOUDRENEW_SWIFT_H
#define SCALECLOUDRENEW_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ScaleCloudRenew",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CScaleCloudSign;
@import CoreData;
@import Foundation;
@import Intents;
@import ObjectiveC;
@import UIKit;
#endif

#import <ScaleCloudRenew/ScaleCloudRenew.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ScaleCloudRenew",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS("_TtC15ScaleCloudRenew10BaseEntity")
@interface BaseEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context SWIFT_UNAVAILABLE;
@end

@class NSString;
@class Team;
SWIFT_CLASS_NAMED("Account")
@interface Account : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull appleID;
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull lastName;
@property (nonatomic) BOOL isActiveAccount;
@property (nonatomic, copy) NSSet<Team *> * _Nonnull teams;
@end

@class NSCoder;
SWIFT_CLASS_NAMED("App") SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(watchos,introduced=5.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=12.0)
@interface App : INObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nullable)identifier displayString:(NSString * _Nonnull)displayString pronunciationHint:(NSString * _Nullable)pronunciationHint OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
SWIFT_CLASS_NAMED("AppID")
@interface AppID : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull bundleIdentifier;
@property (nonatomic, copy) NSDictionary<ALTFeature, id> * _Nonnull features;
@property (nonatomic, copy) NSDate * _Nullable expirationDate;
@property (nonatomic, readonly, strong) Team * _Nullable team;
@end

@class StoreApp;
SWIFT_CLASS_NAMED("AppPermission")
@interface AppPermission : BaseEntity
@property (nonatomic) ALTAppPermissionType _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull permission;
@property (nonatomic, copy) NSString * _Nonnull appBundleID;
@property (nonatomic, copy) NSString * _Nonnull sourceID;
@property (nonatomic, readonly, strong) StoreApp * _Nullable app;
@end

SWIFT_CLASS_NAMED("AppResolutionResult") SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(watchos,introduced=6.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface AppResolutionResult : INObjectResolutionResult
+ (nonnull instancetype)successWithResolvedApp:(App * _Nonnull)resolvedObject SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)disambiguationWithAppsToDisambiguate:(NSArray<App *> * _Nonnull)objectsToDisambiguate SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)confirmationRequiredWithAppToConfirm:(App * _Nullable)objectToConfirm SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)successWithResolvedObject:(INObject * _Nonnull)resolvedObject SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE;
+ (nonnull instancetype)disambiguationWithObjectsToDisambiguate:(NSArray<INObject *> * _Nonnull)objectsToDisambiguate SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE;
+ (nonnull instancetype)confirmationRequiredWithObjectToConfirm:(INObject * _Nullable)objectToConfirm SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE;
@end

@class NSURL;
SWIFT_CLASS_NAMED("AppScreenshot")
@interface AppScreenshot : BaseEntity
@property (nonatomic, readonly, copy) NSURL * _Nonnull imageURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull appBundleID;
@property (nonatomic, readonly, copy) NSString * _Nonnull sourceID;
@property (nonatomic, readonly, strong) StoreApp * _Nullable app;
- (void)awakeFromInsert;
@end

@class ReleaseTrack;
SWIFT_CLASS_NAMED("AppVersion")
@interface AppVersion : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, readonly, copy) NSString * _Nonnull buildVersion;
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
@property (nonatomic, readonly, copy) NSString * _Nullable localizedDescription;
@property (nonatomic, readonly, copy) NSURL * _Nonnull downloadURL;
@property (nonatomic, readonly) int64_t size;
@property (nonatomic, readonly, copy) NSString * _Nullable sha256;
@property (nonatomic, readonly, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nonnull appBundleID;
@property (nonatomic, copy) NSString * _Nullable sourceID;
@property (nonatomic, readonly, strong) StoreApp * _Nullable app;
@property (nonatomic, readonly, strong) StoreApp * _Nullable latestVersionApp;
@property (nonatomic, strong) ReleaseTrack * _Nullable releaseTrack;
@end

@class InstalledExtension;
SWIFT_CLASS_NAMED("InstalledApp")
@interface InstalledApp : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull bundleIdentifier;
@property (nonatomic, copy) NSString * _Nonnull resignedBundleIdentifier;
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, copy) NSString * _Nonnull buildVersion;
@property (nonatomic, copy) NSDate * _Nonnull refreshedDate;
@property (nonatomic, copy) NSDate * _Nonnull expirationDate;
@property (nonatomic, copy) NSDate * _Nonnull installedDate;
@property (nonatomic) BOOL isActive;
@property (nonatomic) BOOL needsResign;
@property (nonatomic) BOOL hasAlternateIcon;
@property (nonatomic) BOOL useMainProfile;
@property (nonatomic, copy) NSString * _Nullable certificateSerialNumber;
@property (nonatomic, copy) NSString * _Nullable storeBuildVersion;
@property (nonatomic) BOOL isRefreshing;
@property (nonatomic, strong) StoreApp * _Nullable storeApp;
@property (nonatomic, strong) Team * _Nullable team;
@property (nonatomic, copy) NSSet<InstalledExtension *> * _Nonnull appExtensions;
@property (nonatomic, readonly, strong) NSSet * _Nonnull loggedErrors;
@property (nonatomic, readonly) BOOL hasUpdate;
@end

SWIFT_CLASS_NAMED("InstalledExtension")
@interface InstalledExtension : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull bundleIdentifier;
@property (nonatomic, copy) NSString * _Nonnull resignedBundleIdentifier;
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, copy) NSDate * _Nonnull refreshedDate;
@property (nonatomic, copy) NSDate * _Nonnull expirationDate;
@property (nonatomic, copy) NSDate * _Nonnull installedDate;
@property (nonatomic, strong) InstalledApp * _Nullable parentApp;
@end

SWIFT_CLASS_NAMED("LoggedError")
@interface LoggedError : BaseEntity
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
@property (nonatomic, readonly, copy) NSString * _Nonnull domain;
@property (nonatomic, readonly) int32_t code;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull userInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull appName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appBundleID;
@property (nonatomic, readonly, strong) StoreApp * _Nullable storeApp;
@property (nonatomic, readonly, strong) InstalledApp * _Nullable installedApp;
@end

@interface LoggedError (SWIFT_EXTENSION(ScaleCloudRenew))
@property (nonatomic, readonly, copy) NSString * _Nonnull localizedDateString;
@end

@class NSConstraintConflict;
SWIFT_CLASS("_TtC15ScaleCloudRenew11MergePolicy")
@interface MergePolicy : RSTRelationshipPreservingMergePolicy
- (BOOL)resolveConstraintConflicts:(NSArray<NSConstraintConflict *> * _Nonnull)conflicts error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSError (SWIFT_EXTENSION(ScaleCloudRenew))
+ (void)alt_setUserInfoValueProviderForDomain:(NSString * _Nonnull)domain provider:(id _Nullable (^ _Nullable)(NSError * _Nonnull, NSString * _Nonnull))provider;
@end

@interface NSError (SWIFT_EXTENSION(ScaleCloudRenew))
@property (nonatomic, readonly, copy) NSString * _Nullable alt_localizedFailure;
@property (nonatomic, readonly, copy) NSString * _Nullable alt_localizedDebugDescription;
@property (nonatomic, readonly, copy) NSString * _Nullable alt_localizedTitle;
- (NSError * _Nonnull)alt_errorWithLocalizedFailure:(NSString * _Nonnull)failure SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nonnull)alt_errorWithLocalizedTitle:(NSString * _Nonnull)title SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;
@class Source;
SWIFT_CLASS_NAMED("NewsItem")
@interface NewsItem : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSDate * _Nonnull date;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull caption;
@property (nonatomic, strong) UIColor * _Nonnull tintColor;
@property (nonatomic) int32_t sortIndex;
@property (nonatomic) BOOL isSilent;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSURL * _Nullable externalURL;
@property (nonatomic, copy) NSString * _Nullable appID;
@property (nonatomic, copy) NSString * _Nullable sourceIdentifier;
@property (nonatomic, strong) StoreApp * _Nullable storeApp;
@property (nonatomic, strong) Source * _Nullable source;
@end

typedef SWIFT_ENUM(NSUInteger, Platform, open) {
  PlatformIos = 0,
  PlatformTvos = 1,
  PlatformMacos = 2,
};

SWIFT_CLASS("_TtC15ScaleCloudRenew11PlatformURL")
@interface PlatformURL : NSManagedObject
@property (nonatomic, readonly) enum Platform platform;
@property (nonatomic, readonly, copy) NSURL * _Nonnull downloadURL;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS_NAMED("RefreshAttempt")
@interface RefreshAttempt : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSDate * _Nonnull date;
@property (nonatomic) BOOL isSuccess;
@property (nonatomic, copy) NSString * _Nullable errorDescription;
@end

@class NSOrderedSet;
SWIFT_CLASS_NAMED("ReleaseTrack")
@interface ReleaseTrack : BaseEntity
@property (nonatomic, readonly, copy) NSString * _Nullable track;
@property (nonatomic, readonly, copy) NSString * _Nullable appBundleID;
@property (nonatomic, readonly, copy) NSString * _Nullable sourceID;
@property (nonatomic, readonly, strong) NSOrderedSet * _Nullable releases;
@property (nonatomic, readonly, strong) StoreApp * _Nullable storeApp;
@end

@interface ReleaseTrack (SWIFT_EXTENSION(ScaleCloudRenew))
/// Defer updates to fields that require storeApp inverse relationship to be set, which is not available in init(),
/// by observing changes to the prop and update the data later
/// NOTE: We use KVO here only coz, ReleaseTrack already has an inverse relationship to StoreAppV2
/// So coredata will actually set the storeApp but only issue is that it happens after init() is complete
/// hence we are using KVO so that one doesn’t need to manually set the value via a setter method
/// However this caused an issue when an object is marked deleted during merge policy conflict resolution, all its props are set to nil by coredata.
/// this causes this KVO observer to be triggered and mutating the deleted entity causing a “coredata error: Mutating removed object”
/// which is now handled by checking if context.deletedObjects doesn’t contain it and version.isDeleted is not true yet
- (void)didChangeValueForKey:(NSString * _Nonnull)key;
@end

SWIFT_CLASS_NAMED("SecureValueTransformer")
@interface ALTSecureValueTransformer : NSSecureUnarchiveFromDataTransformer
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<Class> * _Nonnull allowedTopLevelClasses;)
+ (NSArray<Class> * _Nonnull)allowedTopLevelClasses SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)allowsReverseTransformation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("Source")
@interface Source : BaseEntity
@property (nonatomic) NSInteger version;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nullable groupID;
@property (nonatomic, copy) NSURL * _Nonnull sourceURL;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable localizedDescription;
@property (nonatomic, copy) NSURL * _Nullable websiteURL;
@property (nonatomic, copy) NSURL * _Nullable patreonURL;
@property (nonatomic, strong) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable featuredSortID;
@property (nonatomic, readonly, strong) NSOrderedSet * _Nonnull apps;
@property (nonatomic, readonly, strong) NSOrderedSet * _Nonnull newsItems;
@property (nonatomic, readonly, strong) NSOrderedSet * _Nonnull featuredApps;
- (void)awakeFromInsert;
@end

SWIFT_CLASS_NAMED("StoreApp")
@interface StoreApp : BaseEntity
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull bundleIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nullable subtitle;
@property (nonatomic, readonly, copy) NSString * _Nonnull developerName;
@property (nonatomic, readonly, copy) NSString * _Nonnull localizedDescription;
@property (nonatomic, readonly, copy) NSString * _Nullable category;
@property (nonatomic, readonly, copy) NSURL * _Nonnull iconURL;
@property (nonatomic, readonly, copy) NSArray<NSURL *> * _Nonnull screenshotURLs;
@property (nonatomic, readonly, copy) NSURL * _Nullable downloadURL;
@property (nonatomic, readonly, copy) NSArray<PlatformURL *> * _Nullable platformURLs;
@property (nonatomic, readonly, strong) UIColor * _Nullable tintColor;
@property (nonatomic, readonly, copy) NSString * _Nullable marketplaceID;
@property (nonatomic) BOOL isPledged;
@property (nonatomic, readonly) BOOL isPledgeRequired;
@property (nonatomic, readonly) BOOL isHiddenWithoutPledge;
@property (nonatomic, readonly, copy) NSString * _Nullable pledgeCurrency;
@property (nonatomic, readonly) BOOL prefersCustomPledge;
@property (nonatomic) int32_t sortIndex;
@property (nonatomic, copy) NSString * _Nullable featuredSortID;
@property (nonatomic, readonly, copy) NSString * _Nullable sourceIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nullable version;
@property (nonatomic, readonly, copy) NSDate * _Nullable versionDate;
@property (nonatomic, readonly, copy) NSString * _Nullable versionDescription;
@property (nonatomic, strong) InstalledApp * _Nullable installedApp;
@property (nonatomic, copy) NSSet<NewsItem *> * _Nonnull newsItems;
@property (nonatomic, strong) Source * _Nullable source;
@property (nonatomic, readonly, strong) Source * _Nullable featuringSource;
@property (nonatomic, readonly, strong) AppVersion * _Nullable latestVersion;
@property (nonatomic, readonly, strong) NSOrderedSet * _Nonnull versions;
@property (nonatomic, readonly, strong) NSSet * _Nonnull loggedErrors;
- (void)awakeFromInsert;
@end

@interface StoreApp (SWIFT_EXTENSION(ScaleCloudRenew))
@property (nonatomic, readonly, strong) NSOrderedSet * _Nullable releaseTracks;
@end

SWIFT_CLASS_NAMED("Team")
@interface Team : BaseEntity
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic) ALTTeamType type;
@property (nonatomic) BOOL isActiveTeam;
@property (nonatomic, readonly, strong) Account * _Null_unspecified account;
@property (nonatomic, copy) NSSet<InstalledApp *> * _Nonnull installedApps;
@property (nonatomic, readonly, copy) NSSet<AppID *> * _Nonnull appIDs;
@end

@class NSBundle;
/// Modal 6-digit code entry screen.
/// Present this when .twoFactorRequired fires; dismiss when request is fulfilled.
SWIFT_CLASS("_TtC15ScaleCloudRenew23TwoFactorViewController")
@interface TwoFactorViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSUserDefaults (SWIFT_EXTENSION(ScaleCloudRenew))
@property (nonatomic, copy) NSDate * _Nullable firstLaunch;
@property (nonatomic) BOOL requiresAppGroupMigration;
@property (nonatomic) BOOL textServer;
@property (nonatomic) BOOL sidejitenable;
@property (nonatomic, copy) NSString * _Nullable textInputSideJITServerurl;
@property (nonatomic, copy) NSString * _Nullable textInputAnisetteURL;
@property (nonatomic, copy) NSString * _Nullable customAnisetteURL;
@property (nonatomic, copy) NSString * _Nonnull menuAnisetteList;
@property (nonatomic, copy) NSString * _Nullable preferredServerID;
@property (nonatomic) BOOL isBackgroundRefreshEnabled;
@property (nonatomic) BOOL enableEMPforWireguard;
@property (nonatomic) BOOL isIdleTimeoutDisableEnabled;
@property (nonatomic) BOOL isAppLimitDisabled;
@property (nonatomic) BOOL isBetaUpdatesEnabled;
@property (nonatomic) BOOL customizeAppId;
@property (nonatomic) BOOL isExportResignedAppEnabled;
@property (nonatomic) BOOL isVerboseOperationsLoggingEnabled;
@property (nonatomic) BOOL isMinimuxerConsoleLoggingEnabled;
@property (nonatomic) BOOL isMinimuxerStatusCheckEnabled;
@property (nonatomic) BOOL recreateDatabaseOnNextStart;
@property (nonatomic) BOOL isPairingReset;
@property (nonatomic) BOOL isDebugModeEnabled;
@property (nonatomic) BOOL presentedLaunchReminderNotification;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable legacySideloadedApps;
@property (nonatomic) BOOL isLegacyDeactivationSupported;
@property (nonatomic) BOOL activeAppLimitIncludesExtensions;
@property (nonatomic) BOOL localServerSupportsRefreshing;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable patchedApps;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable trustedSourceIDs;
@property (nonatomic, copy) NSString * _Nullable trustedServerURL;
@property (nonatomic, copy) NSString * _Nullable betaUdpatesTrack;
@property (nonatomic) BOOL isCowExploitSupported;
@property (nonatomic) BOOL permissionCheckingDisabled;
@property (nonatomic) BOOL responseCachingDisabled;
@end

SWIFT_CLASS_NAMED("ViewAppIntent") SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(watchos,introduced=5.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=12.0)
@interface ViewAppIntent : INIntent
@property (nonatomic, strong) App * _Nullable app;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ViewAppIntentResponse;
SWIFT_PROTOCOL_NAMED("ViewAppIntentHandling") SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(watchos,introduced=5.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=12.0)
@protocol ViewAppIntentHandling <NSObject>
- (void)provideAppOptionsCollectionForViewApp:(ViewAppIntent * _Nonnull)intent withCompletion:(void (^ _Nonnull)(INObjectCollection<App *> * _Nullable, NSError * _Nullable))completion SWIFT_AVAILABILITY(watchos,introduced=7.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=14.0);
@optional
- (void)confirmViewApp:(ViewAppIntent * _Nonnull)intent completion:(void (^ _Nonnull)(ViewAppIntentResponse * _Nonnull))completion;
- (void)handleViewApp:(ViewAppIntent * _Nonnull)intent completion:(void (^ _Nonnull)(ViewAppIntentResponse * _Nonnull))completion;
- (App * _Nullable)defaultAppForViewApp:(ViewAppIntent * _Nonnull)intent SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(watchos,introduced=7.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)provideAppOptionsForViewApp:(ViewAppIntent * _Nonnull)intent withCompletion:(void (^ _Nonnull)(NSArray<App *> * _Nullable, NSError * _Nullable))completion SWIFT_AVAILABILITY(watchos,introduced=6.0,deprecated=7.0) SWIFT_AVAILABILITY(ios,introduced=13.0,deprecated=14.0);
@end

SWIFT_CLASS("_TtC15ScaleCloudRenew20ViewAppIntentHandler")
@interface ViewAppIntentHandler : NSObject <ViewAppIntentHandling>
- (void)provideAppOptionsCollectionForViewApp:(ViewAppIntent * _Nonnull)intent withCompletion:(void (^ _Nonnull)(INObjectCollection<App *> * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, ViewAppIntentResponseCode)
@class NSUserActivity;
SWIFT_CLASS_NAMED("ViewAppIntentResponse") SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(watchos,introduced=5.0) SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=12.0)
@interface ViewAppIntentResponse : INIntentResponse
@property (nonatomic, readonly) enum ViewAppIntentResponseCode code;
- (nonnull instancetype)initWithCode:(enum ViewAppIntentResponseCode)code userActivity:(NSUserActivity * _Nullable)userActivity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ViewAppIntentResponseCode, open) {
  ViewAppIntentResponseCodeUnspecified = 0,
  ViewAppIntentResponseCodeReady = 1,
  ViewAppIntentResponseCodeContinueInApp = 2,
  ViewAppIntentResponseCodeInProgress = 3,
  ViewAppIntentResponseCodeSuccess = 4,
  ViewAppIntentResponseCodeFailure = 5,
  ViewAppIntentResponseCodeFailureRequiringAppLaunch = 6,
};

SWIFT_CLASS("_TtC15ScaleCloudRenew17WebViewController")
@interface WebViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewIsAppearing:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)didMoveToParentViewController:(UIViewController * _Nullable)parent;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
