# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later

name: ScaleCloudRenew
options:
  xcodeVersion: "15.4"
  minimumXcodeVersion: "15.4"
settings:
  objectVersion: 56
  base:
    DEFINES_MODULE: "YES"
    PRODUCT_NAME: ScaleCloudRenew
    PRODUCT_MODULE_NAME: ScaleCloudRenew
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "14.0"
targets:
  ScaleCloudRenew:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Resources
        type: folder
        buildPhase: resources
      - path: Sources
        excludes:
          - "**/Info.plist"
          - "**/Makefile.am"
          - "**/Makefile.in"
          - "**/.gitignore"
          - "**/.gitkeep"
          - "**/README*"
          - "**/LICENSE*"
          - "**/*.md"
          - "**/autogen.sh"
          - "**/configure*"
          - "**/config.h.in"
          - "**/*.pc.in"
          - "**/*.dict"
          - "AltStoreCore/Components/Keychain.swift"
          - "RustBridge/lib"
    settings:
      base:
        SKIP_INSTALL: "NO"
        BUILD_LIBRARY_FOR_DISTRIBUTION: "YES"
        PRODUCT_NAME: ScaleCloudRenew
        PRODUCT_MODULE_NAME: ScaleCloudRenew
        SWIFT_VERSION: "5.0"
        DEFINES_MODULE: "YES"
        MODULEMAP_FILE: "$(SRCROOT)/Sources/module.modulemap"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(SRCROOT)/../ScaleCloudGo/prebuilt $(SRCROOT)/../ScaleCloudKit/prebuilt $(SRCROOT)/../ScaleCloudSign/prebuilt $(SRCROOT)/Sources/RustBridge/lib"
        INTENTS_CODEGEN_LANGUAGE: "Swift"
        INTENTS_CODEGEN_VISIBILITY: "public"
        GENERATE_INFOPLIST_FILE: "YES"
        HEADER_SEARCH_PATHS: "$(inherited) $(SRCROOT)/Sources/Roxas $(SRCROOT)/Sources/AltStoreCore"
        OTHER_CPLUSPLUSFLAGS: "$(inherited) -w"
        OTHER_SWIFT_FLAGS: "$(inherited) -suppress-warnings -Xcc -fpermissive"
        OTHER_CFLAGS: "$(inherited) -Wno-error=incompatible-pointer-types"
        GCC_PREPROCESSOR_DEFINITIONS: "$(inherited) unix=1 MARKETPLACE=1"
    dependencies:
      - framework: ../ScaleCloudSign/prebuilt/AltSign.framework
        embed: false
      - framework: ../ScaleCloudGo/prebuilt/ScaleCloudGo.xcframework
        embed: false
      - framework: ../ScaleCloudKit/prebuilt/ScaleCloudKit.framework
        embed: false
      - framework: Sources/RustBridge/lib/RustBridge.xcframework
        embed: false
      - package: Starscream
      - package: KeychainAccess
      - package: ZIPFoundation
      - package: Alamofire
      - package: SwiftyJSON
      - package: SwiftyXMLParser
      - sdk: UIKit.framework
packages:
  Starscream:
    url: https://github.com/daltoniam/Starscream
    from: 4.0.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.0
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: 0.9.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.6.0
  SwiftyJSON:
    url: https://github.com/SwiftyJSON/SwiftyJSON
    from: 5.0.0
  SwiftyXMLParser:
    url: https://github.com/yahoojapan/SwiftyXMLParser
    from: 5.6.0

